### ISSUE TITLE
HSV struct fields are named inconsistent

### ISSUE THREAD

**Issue by jounathaen** [smart-leds-rs/smart-leds#9]
The RBG struct in https://crates.io/crates/rgb names the fields "r", "g" and "b". This crate uses "hue", "sat" and "val".

This is a change that would break dependent applications, but I it would be more consistent to use "h", "s" and "v".

**Comment by david-sawatzke** [comment]
I personally prefer the longer abbreviations for the hsv fields, since it's easier to remember what they refer to that way. With rgb, it's not an issue, so the shorter ones are fine (there are also no obvious tlas).
